input {
  file {
    path => "/logs/access.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "honeytoken_access"
  }
  file {
    path => "/logs/alerts.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "honeytoken_alert"
  }
}

filter {
  if [type] == "honeytoken_access" {
    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }
    geoip {
      source => "[ip_info][geolocation][ip]"
      target => "geoip"
    }
  }
  
  if [type] == "honeytoken_alert" {
    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }
    mutate {
      add_field => {
        "alert_severity" => "high"
      }
    }
  }
}

output {
  if [type] == "honeytoken_access" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "honeytoken-access-%{+YYYY.MM.dd}"
    }
  }
  
  if [type] == "honeytoken_alert" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "honeytoken-alerts-%{+YYYY.MM.dd}"
    }
  }
  
  stdout {
    codec => rubydebug
  }
} 